version: 1

actors:
- webserver

webserver:
  group: server.web
  port: 8123
  routes:
  - path: /quit
    name: quit
    handler: do_quit
  - path: /integrator
    name: integrator
    handler: do_default
