version: 1
formatters:
  simple:
    format: '%(levelname)s %(name)s %(asctime)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: var/log/cco.integrator.log
    maxBytes: 10485760
    backupCount: 3
loggers:
  cco.integrator:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
