version: 1

actors:
  - check-dir
  - worker
  - webserver

check-dir:
  step: checker.check_dir
  path: data
  action:
    message: command
    actor: worker
    command: move-file

worker:
  group: worker
  actions:
    move-file:
      handler: move_file
      target-dir: data/target
      backup-dir: data/backup

webserver:
  group: server.web
  port: 8123
  routes:
    - path: /integrator/
      name: integrator
      handler: do_default
    - path: /quit
      name: quit
      handler: do_quit
    - path: /poll
      name: poll
      handler: do_poll
      timeout: 10
    #- path: /<msg>+
    #  name: default
    #  handler: do_forward
    #  clients: ...

poll-fms:
  start: polling.serve
  url: http://localhost:8123/poll
  http_timeout: 30
  sleep_on_excp: 10
  sleep_on_idle: 0
  #target_mailbox: default
