version: 1

actors:
  - check-dir
#  - webserver

check-dir:
  module: cco.integrator.checker
  step: check_dir
  path: data
  action: 
    actor: worker
    message: move-file

webserver:
  module: cco.integrator.webserver.wsgi
  start: run_waitress
  port: 8123
  routes:
    quit:
      path: /quit
      function: do_quit
    poll:
      path: /poll
      function: do_poll
      timeout: 10
    default:
      path: <msg>
      function: do_forward
      clients: ...

poll_fms:
  start: serve
  module: cco.integrator.polling
  url: http://localhost:8123/poll
  http_timeout: 30
  sleep_on_excp: 10
  sleep_on_idle: 0
  target_mailbox: default

dispatcher:
  receive_timeout: 10

worker:
  module: cco.integrator.worker
  actions:
    move-file:
      function: move_file
      target-path: data/target
