version: 1

actors:
  - check-dir
  - worker
  - webserver

check-dir:
  module: cco.integrator.checker
  step: check_dir
  path: data
  action:
    message: command
    actor: worker
    command: move-file

worker:
  module: cco.integrator.worker
  actions:
    move-file:
      function: move_file
      target-dir: data/target
      backup-dir: data/backup

webserver:
  module: cco.integrator.webserver.wsgi
  start: start_waitress
  port: 8123
  pollable_timeout: 10
  routes:
    quit:
      path: /quit
      function: do_quit
    poll:
      path: /poll
      function: do_poll
      timeout: 10
    default:
      path: <msg>
      function: do_forward
      clients: ...

poll-fms:
  start: serve
  module: cco.integrator.polling
  url: http://localhost:8123/poll
  http_timeout: 30
  sleep_on_excp: 10
  sleep_on_idle: 0
  #target_mailbox: default
