version: 1
formatters:
  simple:
    format: '%(levelname)s %(name)s %(asctime)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  integrator.common:
    level: INFO
    handlers: [console]
    propagate: no
  integrator.webserver:
    level: INFO
    handlers: [console]
    propagate: no
  waitress:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
